#! /bin/bash
if [ $# -lt 1 ]
then
	echo "Not Enough Arguments!"
	exit
fi

case $1 in
	"start" )
	echo "=============== Start HDFS ================"
	ssh hadoop102 /opt/module/hadoop-3.1.3/sbin/start-dfs.sh
	echo "=============== Start YARN ================"
	ssh hadoop103 /opt/module/hadoop-3.1.3/sbin/start-yarn.sh
	echo "========== Start  HistoryServer ==========="
	ssh hadoop102 mapred --daemon start historyserver
		;;

	"stop" )
	echo "=============== Stop HDFS ================"
	ssh hadoop102 /opt/module/hadoop-3.1.3/sbin/stop-dfs.sh
	echo "=============== Stop YARN ================"
	ssh hadoop103 /opt/module/hadoop-3.1.3/sbin/stop-yarn.sh
	echo "========== Stop  HistoryServer ==========="
	ssh hadoop102 mapred --daemon stop historyserver
		;;
	* )
	echo "Invalid Arguments!!"
		;;
esac